- block:
  - name: create deploy dir
    file:
      state: directory
      path: "{{ iroha_deploy_dir }}/conf"

  # Attachable overlay network cannot be created with a `docker_network` module
  - name: create Docker network
    shell: "docker network create -d overlay --attachable {{ iroha_network_name }} || true"
    when: iroha_overlay_network
    run_once: yes

  - name: create Docker network
    docker_network:
      name: "{{ iroha_network_name }}"
    when: not iroha_overlay_network

  - name: generate Docker Compose
    template:
      src: docker-compose.yml.j2
      dest: "{{ iroha_deploy_dir }}/docker-compose.yml"
    notify: restart Iroha
    tags: ["iroha-deploy"]

  - name: generate config files
    template:
      src: config.docker.j2
      dest: "{{ iroha_deploy_dir }}/conf/{{ item.human_hostname }}/config.docker"
    notify: restart Iroha
    loop: "{{ iroha_nodes }}"
    tags: ["iroha-deploy"]

  - name: run Iroha
    docker_service:
      project_src: "{{ iroha_deploy_dir }}"
    tags: ["iroha-deploy"]
  when: iroha_update_runtime_configs
