version: '3'

services:
  node:
    image: hyperledger/iroha:develop-build
    ports:
      - "${IROHA_PORT}:50051"
      - "${DEBUGGER_PORT}:20000"
    environment:
      - IROHA_POSTGRES_HOST=${COMPOSE_PROJECT_NAME}_postgres_1
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - CCACHE_DIR=/tmp/ccache
    # export G_ID=$(id -g $(whoami))
    # export U_ID=$(id -g $(whoami))
    user: ${U_ID:-0}:${G_ID:-0}
    depends_on:
      - postgres
    tty: true
    volumes:
      - ../:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
    command: -c 'max_prepared_transactions=100'

volumes:
  ccache-data:
