version: '3'

services:
  node:
    image: hyperledger/iroha-docker-develop
    ports:
      - "50051:50051"
    environment:
      - IROHA_POSTGRES_HOST=iroha_postgres_1
      - IROHA_POSTGRES_PORT=5432
      - IROHA_POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld
      - IROHA_REDIS_HOST=iroha_redis_1
      - IROHA_REDIS_PORT=6379
      - CCACHE_DIR=/tmp/ccache
    depends_on:
      - redis
      - postgres
    tty: true
    volumes:
      - ../:/opt/iroha
      - ccache-data:/tmp/ccache
    working_dir: /opt/iroha

  redis:
    image: redis:3.2.8

  postgres:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=iroha
      - IROHA_POSTGRES_PASSWORD=helloworld

volumes:
  ccache-data:
